12:46:46 [main] ERROR com.revature.Driver - Login exception was thrown: com.revature.exceptions.LoginException
12:48:52 [main] ERROR com.revature.Driver - Login exception was thrown: com.revature.exceptions.LoginException
12:48:57 [main] INFO  com.revature.services.UserService - User: User [id=16, username=kev5, password=pass5] was created.
12:48:57 [main] INFO  com.revature.Driver - User [id=16, username=kev5, password=pass5]14:11:54 [main] ERROR com.revature.Driver - Login exception was thrown: com.revature.exceptions.LoginException
14:19:35 [main] ERROR com.revature.Driver - Login exception was thrown: com.revature.exceptions.LoginException
14:19:49 [main] INFO  com.revature.services.UserService - User: User [id=0, username=dmart, password=pass] was created.
14:19:49 [main] INFO  com.revature.Driver - User [id=0, username=dmart, password=pass]
14:20:29 [main] ERROR com.revature.Driver - Login exception was thrown: com.revature.exceptions.LoginException
14:20:33 [main] INFO  com.revature.services.UserService - User: User [id=0, username=dmart, password=pass] was created.
14:20:33 [main] INFO  com.revature.Driver - User [id=0, username=dmart, password=pass]
14:20:52 [main] ERROR com.revature.Driver - Login exception was thrown: com.revature.exceptions.LoginException
14:20:58 [main] INFO  com.revature.services.UserService - User: User [id=0, username=dmart, password=pass] was created.
14:20:58 [main] INFO  com.revature.Driver - User [id=0, username=dmart, password=pass]
14:30:02 [main] ERROR com.revature.Driver - Login exception was thrown: com.revature.exceptions.LoginException
14:33:58 [main] ERROR com.revature.Driver - Login exception was thrown: com.revature.exceptions.LoginException
14:34:14 [main] ERROR com.revature.Driver - Login exception was thrown: com.revature.exceptions.LoginException
14:37:36 [main] ERROR com.revature.Driver - Login exception was thrown: com.revature.exceptions.LoginException
15:58:55 [main] ERROR com.revature.Driver - Login exception was thrown: com.revature.exceptions.LoginException
16:01:24 [main] ERROR com.revature.Driver - Login exception was thrown: com.revature.exceptions.LoginException
16:03:20 [main] ERROR com.revature.Driver - Login exception was thrown: com.revature.exceptions.LoginException
16:19:14 [main] ERROR com.revature.Driver - Login exception was thrown: com.revature.exceptions.LoginException
16:31:18 [main] ERROR com.revature.Driver - Login exception was thrown: com.revature.exceptions.LoginException
